### ISSUE TITLE
'SDK' section to include reference to Android/Java project

### ISSUE THREAD

**Issue by dandehavilland** [Work-API/developers.work-api.com#13]
- Prepare Android/Java SDK for public

**Comment by nilsfrers** [comment]
On the dashboard I would suggest we add next to it (Work in progress)

so it would say "Android/Java (work in progress)"

On GitHub, I would suggest to remove the "Not production ready" comment (as I believe that what is there is production ready, there are just elements missing)

The Readme would then say something like "Note: This SDK is not yet complete / under development."
